CREATE DATABASE Cafe
GO	

USE Cafe
GO	
--  Bảng Khu vực 
CREATE TABLE Areas
(
	ID INT IDENTITY PRIMARY KEY,
	Name NVARCHAR(100) UNIQUE NOT NULL,
	IsDelete BIT DEFAULT 0 NOT NULL 
)
GO	
-- Bảng Bàn 
CREATE TABLE TableCoffees 
 (
	ID INT IDENTITY PRIMARY KEY,
	AreaID INT NOT NULL,
	Name NVARCHAR(100) NOT NULL,
	Status INT DEFAULT 0 NOT NULL,
	FOREIGN KEY(AreaID) REFERENCES dbo.Areas(ID)
 )
 GO	
 -- Bảng Loại Sản Phẩm:
 CREATE TABLE ProductTypes
 (
	ID INT IDENTITY PRIMARY KEY,
	Name NVARCHAR(100) UNIQUE NOT NULL,
	IsDelete BIT DEFAULT 0 NOT NULL
 )
 GO	
-- Bảng Đơn vị tính:
 CREATE TABLE Units
 (
	ID INT IDENTITY PRIMARY KEY,
	Name NVARCHAR(100) DEFAULT N'Cốc',
	IsDelete BIT	DEFAULT 0 NOT NULL
 )
 GO	
 --Bảng Các Sản Phẩm:
  CREATE TABLE Products
  (
	ID INT IDENTITY PRIMARY KEY,
	TypeID INT NOT NULL,
	UnitID INT NOT NULL,
	Name NVARCHAR(100) NOT NULL,
	Price DECIMAL(10,2) DEFAULT 0 NOT NULL,
	IsDelete BIT DEFAULT 0 NOT NULL,
	FOREIGN KEY (TypeID) REFERENCES dbo.ProductTypes(ID),
	FOREIGN KEY (UnitID) REFERENCES dbo.Units(ID)
  )
  GO	
  -- Bảng Hóa Đơn:
  CREATE TABLE Bills 
  (
	ID INT IDENTITY PRIMARY KEY,
	TableID INT NOT NULL,
	DateTimeCheckIn DATETIME DEFAULT GETDATE() NOT NULL,
	DateTimeCheckOut DATETIME,
	Total DECIMAL(10,2),
	Status INT DEFAULT 0 NOT NULL,
	IsDelete BIT DEFAULT 0 NOT NULL,
	FOREIGN KEY(TableID) REFERENCES dbo.TableCoffees(ID)
  )
  -- Chi Tiết Hóa đơn:
  GO	
  CREATE TABLE BillDetails
  (
	ID INT IDENTITY PRIMARY KEY,
	BillID INT NOT NULL,
	ProductID INT NOT NULL,
	Number INT DEFAULT 1 NOT NULL,
	Price DECIMAL(10,2) DEFAULT 0 NOT NULL,
	Total DECIMAL(10,2) DEFAULT 0 NOT NULL,
	FOREIGN KEY(BillID) REFERENCES dbo.Bills(ID),
	FOREIGN KEY(ProductID) REFERENCES dbo.Products(ID)
  )
  GO	
  -- Bảng tài Khoản
  CREATE TABLE Accounts
  (	
	ID INT IDENTITY PRIMARY KEY,
	UserName VARCHAR(50) NOT NULL,
	Password VARCHAR(20) NOT NULL,
	Role INT DEFAULT 0 NOT NULL
  )
